const iconDefinitions = [
  { key: 'bold', name: 'text-bolder' },
  { key: 'italic', name: 'text-italic' },
  { key: 'fullscreen', name: 'corners-out' },
  { key: 'fullscreenCompress', name: 'truck' },
  { key: 'underline', name: 'text-underline' },
  { key: 'strikeThrough', name: 'text-strikethrough' },
  { key: 'textColor', name: 'eyedropper-sample' },
  { key: 'backgroundColor', name: 'paint-bucket' },
  { key: 'fontSize', name: 'Aa', template: 'text' },
  { key: 'alignLeft', name: 'align-left', template: 'youcan_icons_special' },
  { key: 'alignCenter', name: 'text-align-center', template: 'youcan_icons_special' },
  { key: 'alignRight', name: 'text-align-right', template: 'youcan_icons_special' },
  { key: 'alignJustify', name: 'text-align-justify', template: 'youcan_icons_special' },
  { key: 'formatOL', name: 'list-numbers' },
  { key: 'formatUL', name: 'list-bullets' },
  { key: 'outdent', name: 'text-outdent' },
  { key: 'indent', name: 'text-indent' },
  { key: 'undo', name: 'arrow-bend-up-left' },
  { key: 'redo', name: 'arrow-bend-up-right' },
  { key: 'emoticons', name: 'smiley-sticker' },
  { key: 'insertLink', name: 'globe' },
  { key: 'specialCharacters', name: 'currency-cny' },
  { key: 'insertHR', name: 'minus' },
  { key: 'insertTable', name: 'table' },
  { key: 'insertVideo', name: 'video-camera' },
  { key: 'insertImage', name: 'image' },
  { key: 'moreText', name: 'dots-three' },
  { key: 'moreParagraph', name: 'dots-three' },
  { key: 'moreMisc', name: 'dots-three' },
  { key: 'moreRich', name: 'dots-three' },
  { key: 'clear', name: 'trash' },
  { key: 'imageUpload', name: 'upload-simple' },
  { key: 'imageByURL', name: 'link' },
  { key: 'imageReplace', name: 'arrows-clockwise' },
  { key: 'imageCaption', name: 'truck' },
  { key: 'imageRemove', name: 'trash' },
  { key: 'imageLink', name: 'link' },
  { key: 'linkOpen', name: 'truck' },
  { key: 'linkEdit', name: 'pencil-simple' },
  { key: 'linkRemove', name: 'trash' },
  { key: 'linkBack', name: 'arrow-bend-up-left' },
  { key: 'linkStyle', name: 'palette' },
  { key: 'imageDisplay', name: 'truck' },
  { key: 'imageStyle', name: 'palette' },
  { key: 'imageAlt', name: 'truck' },
  { key: 'imageSize', name: 'truck' },
  { key: 'imageBack', name: 'arrow-bend-up-left' },
  { key: 'videoReplace', name: 'arrows-clockwise' },
  { key: 'videoRemove', name: 'trash' },
  { key: 'videoDisplay', name: 'truck' },
  { key: 'videoBack', name: 'arrow-bend-up-left' },
  { key: 'videoSize', name: 'truck' },
  { key: 'videoByURL', name: 'link' },
  { key: 'videoEmbed', name: 'code' },
  { key: 'videoUpload', name: 'upload-simple' },
  { key: 'autoplay', name: 'play' },
  { key: 'tableHeader', name: 'truck' },
  { key: 'tableFooter', name: 'truck' },
  { key: 'tableRemove', name: 'trash' },
  { key: 'tableRows', name: 'truck' },
  { key: 'tableColumns', name: 'truck' },
  { key: 'tableBack', name: 'arrow-bend-up-left' },
  { key: 'tableStyle', name: 'palette' },
  { key: 'tableCells', name: 'truck' },
  { key: 'tableCellBackground', name: 'paint-bucket' },
  { key: 'tableCellVerticalAlign', name: 'truck' },
  { key: 'tableCellHorizontalAlign', name: 'truck' },
  { key: 'tableCellStyle', name: 'palette' },
];

export default iconDefinitions;
