name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 8.10.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Navigate to subfolder
        run: cd packages/phoenix

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}