name: 'Storybook Tests'
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 8.10.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: set up pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
  
  
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Log current path
        run: pwd

      - name: Build icons
        run: |
          cd packages/icons
          pnpm run build

      - name: List directory contents
        run: ls -la      

      - name: List contents of packages/alto/node_modules directory
        run: |
          cd packages/alto/node_modules/@youcan/ui-icons
          ls -la

      - name: Build Storybook
        run: pnpm build-storybook --quiet
        working-directory: packages/vue3
      
      - name: Install wait-on
        run: pnpm add -D wait-on
        working-directory: packages/vue3

      - name: Serve Storybook and run tests
        run: pnpm test-storybook:ci
        working-directory: packages/vue3